services:
  mongodb:
    image: mongo:6.0        # Use the official MongoDB image
    container_name: mongodb
    ports:
      -        # Expose MongoDB on port 27017
    networks:
      - backend
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data in a volume
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 2
  llm-service:
    image: paam0101/dexcom-llm
    build:
      context: llm-service
    container_name: llm-service
    ports:
      - "5080:5080"
    networks:
      - backend
  dexcom-service:
    image: paam0101/dexcom-ai
    build:
      context: .
    container_name: dexcom-ai
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/dexcom_db
    depends_on:
      - mongodb
      - llm-service
    restart: on-failure:2
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  mongo_data:
    driver: local