spring:
 application:
  name: dexcom-ai
 profiles:
  active: local
 mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_HOST_USER}
  password: ${MAIL_HOST_PASSWD}
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true

#logging:
# level:
#  root: debug
#  com:
#   spinach:
#    dexcom:
#     ai:
#      services: debug
#   org.springframework.cache: DEBUG
resilience4j:
 retry:
  instances:
   llmService:
    max-attempts: 3
    wait-duration: 500ms
management:
 endpoints:
  web:
   exposure:
    include: health,info
 endpoint:
  health:
   show-details: always
server:
 port: 8080